# Demonstration of the fourth message in the Superdense Coding Protocol

Let's start from the Bell state used in the example of the superdense coding protocol, the Bell state known as $|\Phi^+\rangle$, we add subscripts to distinguish the qubits, subscript A is the qubit sent to Alice and subscript B is the qubit sent to Bob:

$$|\Phi^+\rangle=\tfrac{1}{\sqrt{2}}\Big(|00\rangle+|11\rangle\Big)=\tfrac{1}{\sqrt{2}}\Big(|0_B0_A\rangle+|1_B1_A\rangle\Big)$$

Then in step 2 the $ZX$ gate is applied as part of Alice's protocol (encoding rule for the intended message: $11$). Since this gate is applied to Alice's qubit, then Bob's qubt (the one on the left) remains the same, so that the operation to apply to the state of two qubits is $I\otimes ZX$

\begin{align*}
\Big(I\otimes ZX\Big)\tfrac{1}{\sqrt{2}}\Big(|0_B0_A\rangle+|1_B1_A\rangle\Big) &= \tfrac{1}{\sqrt{2}}\Big[\Big(I\otimes ZX\Big)|0_B0_A\rangle + \Big(I\otimes ZX\Big)|1_B1_A\rangle\Big]\\
&= \tfrac{1}{\sqrt{2}}\Big[\Big(I\otimes Z\Big)|0_B1_A\rangle + \Big(I\otimes Z\Big)|1_B0_A\rangle\Big]\\
&= \tfrac{1}{\sqrt{2}}\Big[-|0_B1_A\rangle + |1_B0_A\rangle\Big]\\
&= \tfrac{1}{\sqrt{2}}\Big(-|01\rangle + |10\rangle\Big)
\end{align*}

In step 3, Bob's protocol is applied, that is, the message is decoded, for this the $CNOT$ gate is applied first with Alice's qubit as the control and Bob's qubit as the target ($CNOT_{AB}$):

$$CNOT_{AB}\Big[\tfrac{1}{\sqrt{2}}\Big(-|0_B1_A\rangle + |1_B0_A\rangle\Big)\Big]=\tfrac{1}{\sqrt{2}}\Big(-|1_B1_A\rangle + |1_B0_A\rangle\Big)$$

Now the gate $H$ must be applied to Alice's qubit, so the operation to apply to the state of two qubits is $I\otimes H=I_B\otimes H_A$

\begin{align*}
I_B\otimes H_A\Big[\tfrac{1}{\sqrt{2}}\Big(-|1_B1_A\rangle + |1_B0_A\rangle\Big)\Big] &= I_B\otimes H_A\Big[\tfrac{1}{\sqrt{2}}\Big(-|1_B\rangle\otimes |1_A\rangle + |1_B\rangle\otimes |0_A\rangle\Big)\Big] \\
&= I_B\otimes H_A\Big[\tfrac{1}{\sqrt{2}}\Big(-|1_B\rangle\otimes |1_A\rangle\Big) + \tfrac{1}{\sqrt{2}}|1_B\rangle\otimes |0_A\rangle\Big] \\
&= I_B\otimes H_A\Big[\tfrac{1}{\sqrt{2}}|1_B\rangle\otimes |0_A\rangle-\tfrac{1}{\sqrt{2}}|1_B\rangle\otimes |1_A\rangle\Big] \\
&= I_B\otimes H_A\Big[\tfrac{1}{\sqrt{2}}|1_B\rangle\otimes |0_A\rangle+\tfrac{1}{\sqrt{2}}|1_B\rangle\otimes \Big(-|1_A\rangle\Big)\Big] \\
&= I_B\otimes H_A\Big[|1_B\rangle\otimes \Big(\tfrac{1}{\sqrt{2}}|0_A\rangle\Big)+|1_B\rangle\otimes \Big(-\tfrac{1}{\sqrt{2}}|1_A\rangle\Big)\Big] \\
&= |1_B\rangle\otimes |1_A\rangle \\
&= |1_B1_A\rangle \\
&= |11\rangle
\end{align*}

**Note that $|11\rangle$ is positive**

<br>

When the $I_B\otimes H_A$ operation is applied, we have to apply $H$ to the rightmost qubit (Alice's) leaves us the state $|1_A,\rangle$ let's see the detail:

$$H\Big(\tfrac{1}{\sqrt{2}}|0\rangle\Big)=\tfrac{1}{\sqrt{2}}\tfrac{1}{\sqrt{2}}\Big(|0\rangle+|1\rangle\Big)=\tfrac{1}{2}\Big(|0\rangle+|1\rangle\Big)$$

$$H\Big(-\tfrac{1}{\sqrt{2}}|1\rangle\Big)=\tfrac{1}{\sqrt{2}}\Big(-\tfrac{1}{\sqrt{2}}\Big)\Big(|0\rangle-|1\rangle\Big)=-\tfrac{1}{2}\Big(|0\rangle-|1\rangle\Big)$$

Now we add both parts:

\begin{align*}
H\Big(\tfrac{1}{\sqrt{2}}|0\rangle\Big) + H\Big(-\tfrac{1}{\sqrt{2}}|1\rangle\Big) &= \tfrac{1}{2}\Big(|0\rangle+|1\rangle\Big) - \tfrac{1}{2}\Big(|0\rangle-|1\rangle\Big)\\
&= \tfrac{1}{2}|0\rangle+\tfrac{1}{2}|1\rangle-\tfrac{1}{2}|0\rangle+\tfrac{1}{2}|1\rangle\\
&= \tfrac{1}{2}|1\rangle+\tfrac{1}{2}|1\rangle\\
&= |1\rangle\\
&= |1_A\rangle
\end{align*}

<br>
<br>
<br>

### Therefore the result for the fourth case is $|11\rangle$, that is, positive

<br>
<br>

# Proof with matrix operations

In [1]:
import numpy as np

In [2]:
ket_0 = np.array([[1+0j],
                  [0+0j]])

ket_1 = np.array([[0+0j],
                 [1+0j]])

In [3]:
ket_00 = np.kron(ket_0, ket_0)
ket_01 = np.kron(ket_0, ket_1)
ket_10 = np.kron(ket_1, ket_0)
ket_11 = np.kron(ket_1, ket_1)

print('ket_00=\n',ket_00)
print('ket_01=\n',ket_01)
print('ket_10=\n',ket_10)
print('ket_11=\n',ket_11)

ket_00=
 [[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]
ket_01=
 [[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]]
ket_10=
 [[0.+0.j]
 [0.+0.j]
 [1.+0.j]
 [0.+0.j]]
ket_11=
 [[0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [1.+0.j]]


We define the gates that we will use

In [4]:
I = np.array([[ 1+0j,  0+0j],
              [ 0+0j,  1+0j]])

X = np.array([[ 0+0j,  1+0j],
              [ 1+0j,  0+0j]])

Z = np.array([[ 1+0j,  0+0j],
              [ 0+0j, -1+0j]])

H_squared = np.array([[ 1+0j,  1+0j],
                      [ 1+0j, -1+0j]])

H = np.multiply(H_squared, 1/(np.sqrt(2)))

CNOT = np.array([[ 1+0j,  0+0j,  0+0j,  0+0j],
                 [ 0+0j,  0+0j,  0+0j,  1+0j],
                 [ 0+0j,  0+0j,  1+0j,  0+0j],
                 [ 0+0j,  1+0j,  0+0j,  0+0j]])

In [5]:
CNOT

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

In [6]:
ZX = np.matmul(Z,X)

ZX

array([[ 0.+0.j,  1.+0.j],
       [-1.+0.j,  0.+0.j]])

The two-qubit gate $I\otimes H$

In [7]:
IoH = np.kron(I, H)

IoH

array([[ 0.70710678+0.j,  0.70710678+0.j,  0.        +0.j,
         0.        +0.j],
       [ 0.70710678+0.j, -0.70710678+0.j,  0.        +0.j,
        -0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.70710678+0.j,
         0.70710678+0.j],
       [ 0.        +0.j, -0.        +0.j,  0.70710678+0.j,
        -0.70710678+0.j]])

Let's create the Bell state that is used in step 1 of the protocol

In [8]:
IoH_ket_00 = np.matmul(IoH, ket_00)

Bell_1 = np.matmul(CNOT, IoH_ket_00)

Bell_1

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j]])

The two-quibit gate that Alice uses to encode the message $I\otimes ZX$

In [9]:
IoZX = np.kron(I, ZX)

IoZX

array([[ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [-1.+0.j,  0.+0.j, -0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j],
       [-0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j]])

The resulting Bell state $-|\Psi^-\rangle$

In [10]:
Bell_4_neg = np.matmul(IoZX, Bell_1)

Bell_4_neg

array([[ 0.        +0.j],
       [-0.70710678+0.j],
       [ 0.70710678+0.j],
       [ 0.        +0.j]])

First part of step three of the protocol, apply the $CNOT$ gate with Alice's qubit as control and Bob's as target

In [11]:
Bell_4_neg_after_cnot = np.matmul(CNOT, Bell_4_neg)

Bell_4_neg_after_cnot

array([[ 0.        +0.j],
       [ 0.        +0.j],
       [ 0.70710678+0.j],
       [-0.70710678+0.j]])

Second part of step three of the protocol, apply gate H to Alice's qubit

In [12]:
Bell_4_neg_after_cnot_after_h = np.matmul(IoH, Bell_4_neg_after_cnot)

Bell_4_neg_after_cnot_after_h

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j]])

**This result is $|11\rangle$, that is, it is positive**